---
# Source: enterprise-gateway/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    nginx.org/websocket-services: enterprise-gateway-ns/enterprise-gateway
  labels:
    app: enterprise-gateway
    component: enterprise-gateway
    chart: enterprise-gateway-3.2.3
    release: enterprise-gateway
    heritage: Helm
    ss.eg-cluster: "test"
  name: enterprise-gateway
  namespace: enterprise-gateway-ns
spec:
  ports:
    - name: ws-tcp-8888
      port: 8888
      targetPort: 8888
    - name: http-response
      port: 8877
      targetPort: 8877
  selector:
    gateway-selector: enterprise-gateway
  sessionAffinity: ClientIP
  type: ClusterIP
