---
# Source: enterprise-gateway/templates/kip-clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kip-controller
  labels:
    app: enterprise-gateway
    component: kernel-image-puller
    chart: enterprise-gateway-3.2.3
    release: enterprise-gateway
    heritage: Helm
    ss.eg-cluster: "test"
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list", "create", "delete"]
