---
# Source: enterprise-gateway/templates/kip-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kernel-image-puller-sa
  namespace: enterprise-gateway-ns
  labels:
    app: enterprise-gateway
    component: enterprise-gateway
    chart: enterprise-gateway-3.2.3
    release: enterprise-gateway
    heritage: Helm
    ss.eg-cluster: "test"
