---
# Source: enterprise-gateway/templates/eg-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: enterprise-gateway-sa
  namespace: default
  labels:
    app: enterprise-gateway
    component: enterprise-gateway
    chart: enterprise-gateway-3.3.0-dev0
    release: release-name
    heritage: Helm
    ss.eg-cluster: "test"
